api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("report/", views.CreateBugView.as_view(), name='report'),
    path("create_project/", views.create_project, name="create_project"),
    path('projects/', views.project_list, name='project_list'),
    path('projects/<int:pk>', views.project_detail, name='project_detail'),
    path('projects/all/', views.project_table, name='projects'),
    path('projects/<int:project_pk>/bugs/', views.project_bugs, name='project_bugs'),
    path('bugs/', views.bug_list, name='bug_list'),
    path('bugs/<int:pk>/', views.bug_detail, name='bug_detail'),
    path('bugs/edit/<int:pk>/', views.bug_edit, name='bug_edit'),
    path('bugs/delete/<int:pk>/', views.bug_delete, name='bug_delete'),

]

authapp/urls.py
from django.urls import path
from .views import edit, dashboard, register, djBugsLogoutView
from django.urls import reverse_lazy
from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetDoneView, PasswordResetView,
                                       PasswordResetCompleteView, PasswordResetConfirmView,
                                       PasswordChangeView, PasswordChangeDoneView,
                                       PasswordResetDoneView)


app_name = 'authapp'

urlpatterns = [
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('dashboard/', dashboard, name='dashboard'),
    path('', LoginView.as_view(template_name='authapp/login.html'), name='login'),
    path('logout/', djBugsLogoutView.as_view(), name='logout'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='authapp/password_change_form.html'), name='password_change'),
    path('password_change/dond/', PasswordChangeDoneView.as_view(template_name='authapp/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='authapp/password_reset_form.html',
        email_template_name='authapp/password_reset_email.html',
        success_url=reverse_lazy('authapp:password_reset_done')), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='authapp/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='authapp/password_reset_confirm.html',
        success_url=reverse_lazy('authapp:login')), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='authapp/password_reset_complete.html'), name='password_reset_complete'),
]

djbugtracker/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name='home'),
    path("authapp/", include("authapp.urls")),
    path("api/", include("api.urls")),

]

authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import settings
# Create your models here.


class UserProfile(AbstractUser):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE, related_name='profile')
    role = models.CharField(max_length=50)
    profile_pic = models.ImageField(blank=True)

authapp/forms.py
from django import forms
from .models import UserProfile


class UserRegistration(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = UserProfile
        fields = ('username', 'first_name', 'last_name', 'email')

        def clean_password2(self):
            cd = self.cleaned_data
            if cd['password'] != cd['password2']:
                raise forms.ValidationError('Passwords don\'t match.')
            return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('first_name', 'last_name', 'email')

authapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse_lazy
from .forms import UserRegistration, UserEditForm
from django.contrib.auth.views import LogoutView
from .models import UserProfile


# Create your views here.

@login_required
def dashboard(request):
    current_user = request.user
    context = {
        "welcome": f"{current_user.first_name}'s Dashboard!",
    }
    return render(request, 'authapp/dashboard.html', context=context)


def register(request):
    if request.method == 'POST':
        form = UserRegistration(request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(
                form.cleaned_data.get('password')
            )
            new_user.save()
            return render(request, 'authapp/register_done.html')
    else:
        form = UserRegistration()

    context = {
        "form": form
    }

    return render(request, 'authapp/register.html', context=context)


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        if user_form.is_valid():
            user_form.save()
    else:
        user_form = UserEditForm(instance=request.user)
    context = {
        'form': user_form,
    }
    return render(request, 'authapp/edit.html', context=context)


class djBugsLogoutView(LogoutView):
    def get_success_url(self):
        return reverse_lazy('home')

authapp/templates/authapp/dashboard.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock title %}
{% block content %}
    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-lg-6 text-center">
                <h1 class="heading-projects">{{ welcome }}</h1>
            </div>
        </div>
    </div>
    <div class="container my-5">
        <div class="row justify-content-center align-items-center">
            <div class="col-lg-6 text-center">
                <a href="{% url 'authapp:edit' %}" class="btn btn-custom">Edit Your Profile</a> or
                <a href="{% url 'authapp:password_change' %}" class="btn btn-warning">Change your password</a>
            </div>
        </div>
    </div>
{% endblock content %}

authapp/templates/authapp/edit.html
{% extends "base.html" %}
{% load django_bootstrap5 %} {% load widget_tweaks %}
{% block title %}Edit{% endblock title %}
{% block content %}
    <div class="container login-margin">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <h1 class="heading-projects">Edit your account</h1>
                <p class="description-text">You can edit your account using the follow form</p>
                <form action="" method="post" class="form">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    {% bootstrap_button "Submit" button_type="submit" button_class="btn btn-custom" %}
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

authapp/templates/authapp/login.html
{% extends 'base.html' %} {% block title %} Login {% endblock %}

{% load widget_tweaks %} {% load django_bootstrap5 %}

{% block content %}
    <div class="container login-margin">
        <div style="text-align: center;">
            <h1 class="heading-projects mb-5">Log-in</h1>
            {% if form.errors %}
                {% bootstrap_alert "Incorrect Username or Password" alert_type="danger"%}

            {% else %}

            {% endif %}
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <form action="" method="post" class="form m-auto">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    {% bootstrap_button "Submit" button_type="submit" button_class="btn btn-custom" %}
                    <p><a class="mt-3" href="{% url 'authapp:password_reset' %}">Forgotten your password?</a></p>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

authapp/templates/authapp/password_change_form.html
{% extends "base.html" %} {% load widget_tweaks %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6">

                <h2>Change Your Password</h2>
                <p>Use the form below to change your Password</p>
                <form action="" method="post" class="form">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    {% bootstrap_button "Submit" button_type="submit" button_class="btn btn-custom" %}
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

authapp/templates/authapp/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Password reset{% endblock %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 text-center">
                <h2 class="heading-projects">Password set</h2>
                <p class="description-text">Your password has been set. You can
                    <a href="{% url 'authapp:login' %}">log in now</a></p>
            </div>
        </div>
    </div>
{% endblock %}

authapp/templates/authapp/password_reset_confirm.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}Reset your password{% endblock %}
{% block content %}
<h1 class="heading-projects">Reset your password</h1>
{% if validlink %}
<p class="description-text">Please enter your new password twice:</p>
<form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button "Submit" button_type="submit" button_class="btn btn-custom" button_value="Change my password" %}

</form>
{% else %}
    {% bootstrap_alert "The password reset link was invalid, possibly because it has already been used. Please request a new reset." alert_type="danger" %}
{% endif %}
{% endblock %}

authapp/templates/authapp/password_reset_done.html
{% extends "base.html" %}
{% block title %}Reset your password{% endblock %}
{% block content %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 text-center">
                <h2 class="heading-projects">Reset your password</h2>
                <p class="description-text">Instructions have been emailed for resetting your password.
                </p></div>
        </div>
    </div>
{% endblock %}

authapp/templates/authapp/password_reset_email.html
Someone asked for password reset for email {{email}}.Follow the Link below
{{ protocol }}://{{ domain }}{% url "authapp:password_reset_confirm"
uidb64=uid token=token %}

authapp/templates/authapp/password_reset_form.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}Reset your password

{% endblock title %}
{% block content %}
<div class="container">
    <h2>Forgotten your Password</h2>
    <p>Enter your email address to obtain a new password</p>
    <form action="" method="post" class="form ">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button "Submit" button_type="submit" button_class="btn btn-custom" %}
    </form>
</div>
{% endblock content %}

authapp/templates/authapp/register.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}Registration{% endblock title %}
{% block content %}
    <h1 class="heading-projects text-center my-5">Registration</h1>
    {% if form.errors %}
        {% bootstrap_alert "There was an error with registration!" alert_type="danger" %}
    {% endif %}
    <div class="container my-5">
        <div class="row justify-content-center align-items-center">
            <div class="col-lg-6 text-center">
                <form action="" method="post" class="form container">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    {% bootstrap_button "Submit" button_type="submit" button_class="btn btn-custom" %}
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

authapp/templates/authapp/register_done.html
{% extends "base.html" %}
{% block content %}
    <div class="container login-margin">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <h1 class="heading-projects">Welcome {{ new_user.first_name }}!</h1>
                <p class="description-text">Your account has been successfully created. Now you can <a
                        href="{% url 'authapp:login' %}">log in</a>.</p>
            </div>
        </div>
    </div>
{% endblock content %}