api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("report/", views.CreateBugView.as_view(), name='report'),
    path("create_project/", views.create_project, name="create_project"),
    path('projects/', views.project_list, name='project_list'),
    path('projects/<int:pk>', views.project_detail, name='project_detail'),
    path('projects/all/', views.project_table, name='projects'),
    path('projects/<int:project_pk>/bugs/', views.project_bugs, name='project_bugs'),
    path('bugs/', views.bug_list, name='bug_list'),
    path('bugs/<int:pk>/', views.bug_detail, name='bug_detail'),
    path('bugs/edit/<int:pk>/', views.bug_edit, name='bug_edit'),
    path('bugs/delete/<int:pk>/', views.bug_delete, name='bug_delete'),

]

authapp/urls.py
from django.urls import path
from .views import edit, dashboard, register, djBugsLogoutView
from django.urls import reverse_lazy
from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetDoneView, PasswordResetView,
                                       PasswordResetCompleteView, PasswordResetConfirmView,
                                       PasswordChangeView, PasswordChangeDoneView,
                                       PasswordResetDoneView)


app_name = 'authapp'

urlpatterns = [
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('dashboard/', dashboard, name='dashboard'),
    path('', LoginView.as_view(template_name='authapp/login.html'), name='login'),
    path('logout/', djBugsLogoutView.as_view(), name='logout'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='authapp/password_change_form.html'), name='password_change'),
    path('password_change/dond/', PasswordChangeDoneView.as_view(template_name='authapp/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='authapp/password_reset_form.html',
        email_template_name='authapp/password_reset_email.html',
        success_url=reverse_lazy('authapp:password_reset_done')), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='authapp/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='authapp/password_reset_confirm.html',
        success_url=reverse_lazy('authapp:login')), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='authapp/password_reset_complete.html'), name='password_reset_complete'),
]

djbugtracker/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name='home'),
    path("authapp/", include("authapp.urls")),
    path("api/", include("api.urls")),

]

templates/base.html
{% load static %} {% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>{% block title %}Bug Tracker{% endblock %}</title>
    <!-- Bootstrap -->
    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
            crossorigin="anonymous"
    />
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com"/>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
    <link
            href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;600;700&family=Sacramento&display=swap"
            rel="stylesheet"
    />
    <!-- HTMX -->
    <script src="https://unpkg.com/htmx.org@1.8.5"
            integrity="sha384-7aHh9lqPYGYZ7sTHvzP1t3BAfLhYSTy9ArHdP3Xsr9/3TlGurYgcPBoFmXX2TX/w"
            crossorigin="anonymous"></script>
    <!-- Custom Styles -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
<div class="content">
    <header class="header">
        <nav class="navbar navbar-dark navbar-expand-lg px-5">
            <div class="container-fluid">
                <a class="navbar-brand colors" href="{% url 'home' %}">djBugs</a>
                <button
                        class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarNavAltMarkup"
                        aria-controls="navbarNavAltMarkup"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div
                        class="collapse navbar-collapse justify-content-end"
                        id="navbarNavAltMarkup"
                >
                    <div class="navbar-nav">

                        {% if user.is_authenticated %}
                            <a class="nav-link colors" href="{% url 'authapp:dashboard' %}">Dashboard</a>
                            <a class="nav-link colors" href="{% url 'create_project' %}">Create Project</a>
                            <a class="nav-link colors" href="{% url 'projects' %}">Projects</a>
                            <a class="nav-link colors" href="{% url 'report' %}">Report Bug</a>

                            <a class="nav-link colors" href="{% url 'authapp:logout' %}">Logout</a>
                        {% else %}
                            <a class="nav-link colors" href="{% url 'authapp:login' %}">Login</a>
                            <a class="nav-link colors" href="{% url 'authapp:register' %}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>
    {% block content %}

    {% endblock content %}
</div>
<!-- Footer -->
<footer class="footer">
    <div class="container-fluid mt-5 text-center text-lg-start">
        <div class="container d-flex justify-content-center py-5 gap-3">
            <a href="https://github.com/laffchem" target="_blank" rel="noopener"
            ><i class="fa-brands fa-github icons"></i
            ></a>

            <a href="https://twitter.com/laffchem" target="_blank" rel="noopener"
            ><i class="fa-brands fa-twitter icons"></i
            ></a>
            <a
                    href="https://www.linkedin.com/in/john-laffey/"
                    target="_blank"
                    rel="noopener"
            ><i class="fa-brands fa-linkedin-in icons"></i
            ></a>
        </div>
        <div class="email-box text-center mb-5">
            <a
                    class="email"
                    href="mailto:laffeychem@gmail.com"
                    target="_blank"
                    rel="noopener"
            >laffeychem@gmail.com</a
            >
        </div>

        <!-- Copyright -->
        <div class="text-center px-3 pt-1 pb-3">
            <h3 class="copyright">© Copyright {% now "Y" %}</h3>
        </div>
    </div>
</footer>

<script
        src="https://kit.fontawesome.com/0adf073ec6.js"
        crossorigin="anonymous"
></script>
<script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"
></script>

</body>
</html>

templates/home.html
{% extends 'base.html' %} {% block title %}djBugs{% endblock %} {% block content %}

{% if user.is_authenticated %}
<h1>Authenticated Home Page</h1>
{% else %}
<h1>Non-Authenticated Home Page</h1>
{% endif %}
{% endblock %}